version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_odoo
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_odoo
    restart: unless-stopped
    ports:
      - "8000:8080"

volumes:
  pgdata:
